#!/bin/bash

# This is an All-in-one script to run simple and long and short commands
# with a few keystrokes

update() {
sudo apt update -yy
sudo apt upgrade -yy
sudo apt dist-upgrade -yy
sudo apt full-upgrade -yy
}

help() {
echo "This program/script uses GNU General Public License
	This is an All-in-one script that you can use to do all sorts of things to updateing to backing up /home dir formatting USBs
	-U	updates the system
	-I	installs software
	-h	Displays this help page

	Credits: nonameman12 (founder and current mantainer)"
}

if [ "$1" == "-U" ]; then
	update
	exit
fi

if [ "$1" == "-I" ]; then
	sudo apt-get install "$2"
	exit
fi

if [ "$1" == "-h" ]; then
	help
	exit
fi

if [ "-n" "$1" ]; then
	echo "Error: Invalid argument please use 'AIO -h' for the help page"
	exit 1
fi

exit
